### PR TITLE
Add jsonapi rb benchmark test

### PR DESCRIPTION
**Pull request by minsikzzang**
As mentioned in https://github.com/Netflix/fast_jsonapi/issues/12 and https://github.com/Netflix/fast_jsonapi/issues/44, added benchmark test with `jsonapi-rb`

It's hard to make direct comparison, because `jsonapi-rb` renders `relationships` only when we include.

e.g.) `AMS` / `fast_jsonapi` render movie class without including =>
```
  { 
    ...,
    "relationships" : {
      "actors" : {"data":[{"id":"1","type":"actor"} .... ]},
  }
```

`jsonapi-rb` render movie class without including => 
```
{
  ...,
  "relationships" : {
    "actors" : { "meta" : { "included" : false } .... ]},
}
```

* Benchmark results x 1000
```
Serialize to JSON string 1000 records
Serializer      Records    Time
AMS serializer  1000       369.62 ms
jsonapi-rb serializer 1000       32.99 ms
Fast serializer 1000       10.31 ms


Serialize to JSON string 1000 with includes and meta
Serializer      Records    Time
AMS serializer  1000       509.1 ms
jsonapi-rb serializer 1000       91.17 ms
Fast serializer 1000       20.82 ms
```

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Can you share benchmarks results here? 😊

**Comment by NullVoxPopuli** [comment]
would it make sense to have additional comparisons?

with / without includes?

with / without sparse fieldsets?

with / without relationships (specifically belongs to / has many / both) ?

**Comment by NullVoxPopuli** [comment]
I think it'd also be interesting to see how this interacts with ActiveRecord. Looking at the has_one 'extension', it looks like it's doing `object.relationship.id`, which may or may not cause a DB hit, which wouldn't be required if the foreign key is already on `object`, ya know/

**Comment by bf4** [comment]
@grossadamm fwiw, I did some goofy shell comparison of serializations (jq and diff) in [https://github.com/rails-api/active_model_serializers/blob/benchmarks/benchmarks/serialization_libraries/compare.sh](https://github.com/rails-api/active_model_serializers/blob/b30b8cae7388ef1554e484a14c903b44ff41c1c5/benchmarks/serialization_libraries/compare.sh)

**Comment by NullVoxPopuli** [comment]
The shell comparison are super valuable. When I initially did a jsonapi-rb vs AMS comparison, I didn't take into consideration the different default outputs.

A true comparison should have as-equal-as-possible json outputs.

**Comment by shishirmk** [comment]
@minsikzzang Thank you this is super helpful.

**Pull request merged**
