### PR TITLE
Links within data

### PR DESCRIPTION
**Pull request by jshow**
Links within data and includes - Uses AMS syntax

Also renders links within nested includes

```
class MovieSerializer
  include FastJsonapi::ObjectSerializer
...
  link(:public_url) do |movie_object|
    "http://movies.com/#{movie_object.id}"
  end
end
```

### CODE REVIEW

**Comment by shishirmk** [comment]
Looks like this pull request combines nested includes and links within data. I would like to look at them as separate features to support. 

I like your interface for creation links within data. it looks similar to custom attribute support
```

**Comment by shishirmk** [comment]
@jshow any chance you would be able to fix this? I would really love to add this feature before the next release

**Comment by chagar** [comment]
What needs to be done with this, just remove some code and fix the merge conflict?

**Comment by jshow** [comment]
I'm far to busy to get back to this branch this week

fyi, the nested_includes branch was brought in because I needed links within nested_includes

**Comment by jshow** [comment]
@shishirmk early next week I'll merge `dev` in, thus we'll get links within data and within `nested includes`

**Comment by jshow** [comment]
@shishirmk , `dev` has been merged in - one warning message, but I think that's from efforts done elsewhere

lmk how I can help at this stage - docs are outstanding

**Comment by shishirmk** [comment]
I am planning to make some changes after merging this pull request and docs

**Pull request merged**
