### PR TITLE
Add params to set_id block arguments

### LINKED ISSUE #373: Set id dynamically
Being able to dynamically apply data passed in as options is super helpful:

```ruby
link :personalized_url do |object, params|
  "http://movies.com/#{object.name}-#{params[:user].reference_code}"
end
```

However, I need to apply the id dynamically, which currently doesn't seem possible. Something like:
```ruby
class SomethingSerializer
  include FastJsonapi::ObjectSerializer

  set_id do |_object, params|
    params[:id]
  end
end

# then...
SomethingSerializer.new(Something, { params: { id: my_custom_id } })
```

I saw this PR, https://github.com/Netflix/fast_jsonapi/pull/331, which I commented on, but figured it'd be good to start an issue too.

That PR was a step in the right direction, but I noticed this still doesn't exactly follow the same behaviour as attributes. You can't pass a custom params to the block like you can with attributes.

It seems the code for handling set_id is quite separate from attributes but maybe it's still possible to add that?

### PR DESCRIPTION
**Pull request by henvo**
Pull request #331 added a block to the ObjectSerializer.set_id class
method, which allows passing a block to the set_id method. Currently
this block takes only one argument `record`:

```
set_id do |record|
  "#{record.name.downcase}-#{record.id}"
end
```

This PR adds another argument `params` to the block:

```
set id do |record, params|
  params[:admin] ?  record.id : "#{record.name.downcase}-#{record.id}"
end
```

This customization can be useful in situation where we serve different
clients that may need different IDs. One nice side effect is also that
the `set_id` method has the same method signature as the `attribute`
method.

This PR fixes #373

### CODE REVIEW

**Comment by manojmj92** [comment]
@henvo thanks for the PR! Can you please update the Readme as well?

**Comment by henvo** [comment]
@manojmj92 Thanks for your reply - I updated the README. Hope this fits.

**Comment by marcusg** [comment]
hey guys, any updates on this?

**Comment by rahul342** [comment]
@manojmj92 @shishirmk This feature is super useful. What would be needed to move this forward? Thanks!

**Comment by shishirmk** [comment]
Fix the conflicts with dev and will merge this in

**Comment by henvo** [comment]
@shishirmk The conflicts were already resolved by `bc547ce`

**Comment by pyrabbit** [comment]
Would love to see this merged -- anything I can do to help?

**Comment by phlegx** [comment]
This should also be implemented for `set_type`. Read discussion here #126.

**Comment by henvo** [comment]
@shishirmk Can you merge this in?

**Comment by kapilnarula** [comment]
It seems Netflix has abandoned this project. The existing community created
a new fork to continue support for this project. Please refer

https://github.com/fast-jsonapi/fast_jsonapi

**Comment by henvo** [comment]
Moved to https://github.com/fast-jsonapi/fast_jsonapi/pull/16

**Pull request closed without merging**
