### PR TITLE
fix ActiveRecord ConnectionNotEstablished when ActiveRecord isnt requ…

### PR DESCRIPTION
**Pull request by dks17**
I hope it fixes  ActiveRecord::ConnectionNotEstablished problem #121.
Reference #76.

### CODE REVIEW

**Comment by dks17** [comment]
Hello @guilleiguaran I saw your #76 pr.
Could you please pull this pr and check it in your case. Or add to your Gemfile:
```ruby
gem 'fast_jsonapi', github: 'dks17/fast_jsonapi', branch: 'fix_activerecord'
```

**Comment by shishirmk** [comment]
@guilleiguaran please test in your case and let me know so that i can merge this

**Comment by shishirmk** [comment]
@dks17 is this fix needed after v1.1.0 release?

**Comment by guilleiguaran** [comment]
I'm going to test this but I suspect that there might be a problem when fast_jsonapi is required before than Active Record.

**Pull request merged**
