### PR TITLE
Add scope to be able to serialize context aware

### PR DESCRIPTION
**Pull request by fongfan999**
This PR relates to #139 and #145

### CODE REVIEW

**Comment by shishirmk** [comment]
How do you generally set scope? I am wondering if this should be something that is set in the serializer itself just like key_transform etc? 

Does the way you set scope change every time you invoke the serializer or is there a convention that is followed to derive the scope?

**Comment by fongfan999** [comment]
Hi @shishirmk, 

The `scope` is generally `current_user`, `view_context`, ... And of course, it will not change every time we invoke the serializer.

We can pass `scope` as options on the fly like this:

```ruby
class MovieSerializer
  include FastJsonapi::ObjectSerializer
  
  attribute :name do |object|
    # We can access the `:scope` as here
    scope.admin? ? object.admin_name : object.name
  end
end

options = {}
options[:meta] = { total: 2 }
options[:include] = current_user

MovieSerializer.new(movie, options).serialized_json
```

Please let me know if it didn't make sense. Thank you

**Comment by mhluska** [comment]
Are there any updates on this one? It looks like the merge conflict is an easy fix.

**Comment by jshow** [comment]
I've been too busy to fix the conflict, if you have the time I'd appreciate it

Mostly waiting for comments and someone to merge it to dev - I'm using this branch in production presently

**Comment by mhluska** [comment]
@jshow: https://github.com/Netflix/fast_jsonapi/pull/171

**Comment by shishirmk** [comment]
Merged #171

**Comment by rromanchuk** [comment]
This scope addition got me thinking about my design paradigms. I have many serializers that depend on my `rails` current_user, since this is just being added now i'm wondering if my solutions are poorly designed. 

Here's an example attribute that checks a simple hash if the current logged in user has viewed the object. There is no n+1 or required join, just an existence check of the logged in user. Let's say there is no scope support, how would you ever be able to accomplish this? 

```ruby
attribute :viewed_by_current_user do |object|
   current_user ? object.viewed_by?(current_user) : false
end
```

It might be bad habit from always having access to this scope from view templates

**Pull request closed without merging**
