### PR TITLE
Documentation for polymorphic association

### PR DESCRIPTION
**Pull request by vovimayhem**
# What does this PR do?

* Adds documentation about how to set up polymorphic associations

### CODE REVIEW

**Comment by vovimayhem** [comment]
I didn't knew how to document an option that can take either a `true` or a `Hash` with object class -> `record_type`, so I added two rows to the table.

**Comment by vovimayhem** [comment]
@shishirmk On hindsight, I'm thinking that the `polymorphic` customization in the serializer DSL could be better... I'll start another discussion for this.

**Comment by vovimayhem** [comment]
...see #72

**Comment by shishirmk** [comment]
This should have probably been part of `1.1.0`. I will merge it in soon

**Pull request merged**
