### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ritaly**
That's quite important info ;)

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Rails 4.2 is supported also: https://github.com/Netflix/fast_jsonapi/blob/dev/fast_jsonapi.gemspec#L23

**Comment by ritaly** [comment]
yes, but we've got an error with active record version :)

**Comment by guilleiguaran** [comment]
@ritaly can you try this in your Gemfile:

```ruby
gem 'fast_jsonapi', github: 'Netflix/fast_jsonapi', branch: 'dev'
```

and report here if it works correctly.

**Comment by mknycha** [comment]
Thanks for you answer. I tried to install the gem from the default source, but got the error:
```
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 4.2.10)

  In Gemfile:
    fast_jsonapi was resolved to 1.0.17, which depends on
      activerecord (~> 5.0)

    kaminari-bootstrap was resolved to 3.0.1, which depends on
      rails was resolved to 4.2.10, which depends on
        activerecord (= 4.2.10)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
It turned out that after `gem 'fast_jsonapi', github: 'Netflix/fast_jsonapi', branch: 'dev'` gem was installed correctly. In that case, could you please update gem version in [ruby gem source](https://rubygems.org/gems/fast_jsonapi/versions/1.0.17), or write in README which source to use?

**Comment by mknycha** [comment]
Or are you planning to merge 'dev' branch into master, so that Rails 4.2 will be supported in the next release? We just want to make sure we are using the supported version of this gem.

**Comment by guilleiguaran** [comment]
@mknycha that's right, Rails 4.2 will be supported in next release.

**Comment by mknycha** [comment]
Ok thank you.

**Comment by shishirmk** [comment]
Thanks for responding @guilleiguaran @mknycha the plan is to create a release branch next week and have a release out and them merge to master following the git flow https://jeffkreeftmeijer.com/git-flow/ for our releases.

**Pull request closed without merging**
